version: "3"
services:
  rtsp-server:
    image: bluenviron/mediamtx:1.12.0-ffmpeg
    container_name: rtsp_server
    ports:
      - "8554:8554"
      - "1935:1935"   # fix lại cổng RTMP đúng
      - "9997:9997"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    environment:
      - MTX_LOGLEVEL=info
    networks:
      - ai_cam_net

  webcam-streamer:
    image: jrottenberg/ffmpeg:4.4-ubuntu
    container_name: webcam_streamer
    privileged: true

    devices:
      - "/dev/video0:/dev/video0"
    command: >
      -loglevel debug
      -f v4l2 -input_format yuyv422 -video_size 640x480 -framerate 30 -i /dev/video0
      -vf format=yuv420p
      -vcodec libx264 -preset ultrafast -tune zerolatency
      -f rtsp rtsp://rtsp-server:8554/webcam

    depends_on:
      - rtsp-server
    networks:
      - ai_cam_net
    stop_signal: SIGINT
    restart: "no"

networks:
  ai_cam_net:
    driver: bridge
